### PR TITLE
WIP: Docs migration to dedicated docs subproject 

### PR DESCRIPTION
**Pull request by benhutchison**
Docs migration to dedicated docs subproject with broader classpath, so docs can mention non-core library features as per #93 

*Not complete/working*. Im a bit stuck and need some guidance.

In this version, if I load SBT and do:
```
> docs/generateWebsite
```
I see output like: 
```
...
[info]   Generate the website
[info]     + the user guide
[info]
[info] Total for specification Website
[info] Finished in 4 seconds, 64 ms
...
```
..however there's no HTML files where I'd expect them:
```
[ben_hutchison@VIC017588M eff docs-refactor]$ ls docs/jvm/target/specs2-reports/site/
css		images		javascript	templates
```

### CODE REVIEW

**Comment by etorreborre** [comment]
I'm going to checkout your branch and see if I can make sense of it. I remember having issues in the past as well.

**Comment by etorreborre** [comment]
I haven't tried to work again on the `generateWebsite` task but if you want to at least produce the html doc you can output it with `docs:testOnly *index -- html all html.nostats` and it should be produced in `docs/target/specs2-reports`.

**Comment by etorreborre** [comment]
Hi @benhutchison I tried the `docs/generateWebsite` command and it works for me. That being said a user said on gitter that html generation was not working for him because of a path separator issue, he is on Windows. I don't think that's the case for you but maybe I need to debug this.

**Comment by benhutchison** [comment]
OK, Im confused by SBT on a good day but today is not a good day so Im _superconfused_ 

Rolling up a couple of hours experimentation into one commit and some results:

If the `docs` subproject is where all the site gen happens, then it seems unnecessary to have any settings related to site gen elsewhere. So I tried doing that.

There are two problems. 

1. The site seems to be generated into a `jvm` subdir and I cant figure out why. Observe:

```
> docs/generateWebsite
[info] Updating {file:/Users/ben_hutchison/swork/eff/}coreJVM...
... lots of output redacted ...
[info] Website
[info]
[info]   Generate the website
[info]     + the user guide
[info]
[info] Total for specification Website
[info] Finished in 4 seconds, 221 ms
[info] 1 example, 11 expectations, 0 failure, 0 error
[info]
[success] Total time: 37 s, completed Nov 22, 2017 5:19:31 PM
```
But then:
```
[ben_hutchison@VIC017588M eff docs-refactor]$ ll docs/target/specs2-reports/
total 0
drwxr-xr-x    3 ben_hutchison  833630939   102 Nov 22 17:19 .
drwxr-xr-x    7 ben_hutchison  833630939   238 Nov 22 17:19 ..
drwxr-xr-x  143 ben_hutchison  833630939  4862 Nov 22 17:19 stats
```
only `stats`, but where is the `site`..?
```
[ben_hutchison@VIC017588M eff docs-refactor]$ ll docs/jvm/target/specs2-reports/site/
total 120
drwxr-xr-x  17 ben_hutchison  833630939   578 Nov 22 17:19 .
drwxr-xr-x   3 ben_hutchison  833630939   102 Nov 22 17:19 ..
-rw-r--r--   1 ben_hutchison  833630939   167 Nov 22 17:19 body--1532971178
-rw-r--r--   1 ben_hutchison  833630939  9674 Nov 22 17:19 body--207776263
-rw-r--r--   1 ben_hutchison  833630939  2443 Nov 22 17:19 body--237095434
-rw-r--r--   1 ben_hutchison  833630939  2415 Nov 22 17:19 body--748951328
-rw-r--r--   1 ben_hutchison  833630939  4059 Nov 22 17:19 body--795377338
-rw-r--r--   1 ben_hutchison  833630939  8001 Nov 22 17:19 body--899807026
-rw-r--r--   1 ben_hutchison  833630939  3384 Nov 22 17:19 body--980174464
-rw-r--r--   1 ben_hutchison  833630939  3632 Nov 22 17:19 body-1204595578
-rw-r--r--   1 ben_hutchison  833630939  4365 Nov 22 17:19 body-213114622
-rw-r--r--   1 ben_hutchison  833630939  2049 Nov 22 17:19 body-74718953
drwxr-xr-x  12 ben_hutchison  833630939   408 Nov 22 17:19 css
drwxr-xr-x  18 ben_hutchison  833630939   612 Nov 22 17:19 images
drwxr-xr-x  12 ben_hutchison  833630939   408 Nov 22 17:19 javascript
-rw-r--r--   1 ben_hutchison  833630939  3484 Nov 22 17:19 specs2.html
drwxr-xr-x   3 ben_hutchison  833630939   102 Nov 22 17:19 templates
```
Where did `jvm` come from? SBT seems to know nothing about it either!?
```
> inspect docs/generateWebsite:target
[info] Setting: java.io.File = /Users/ben_hutchison/swork/eff/docs/target
```
Also, a question for you @etorreborre: does what files appear under `docs/jvm/target/specs2-reports/site/` above look correct to you? When I try `open docs/jvm/target/specs2-reports/site/specs2.html` I get a garbled page full of `$vars`, is that right somehow?


2. I cant figure out how to mention the docs-scoped generateWebsite task as a release step

**Comment by benhutchison** [comment]
Have found a better solution in #126

**Pull request closed without merging**
