### PR TITLE
Added "packing" implicits for member instances

### LINKED ISSUE #56: Provide and document easy to have shorter method signatures
Hi,

I've recently been starting to use eff. And it's amazing, thanks for building this!

However what keeps bugging me is that it leads to fairly long method signatures for monad stacks with many effects

```
def foo[R : _foo : _bar : _baz : ...](myArg: MyInputType): MyOutputType
```

Is there an established best practice for defining aliases for long chains of effect context bounds? If so, could you please add that to the documentation?

Thanks!

### PR DESCRIPTION
**Pull request by etorreborre**
The final solution looks simple, but it took me forever to get there and I'm still quite afraid to test it in more "real" conditions.

@boggle could you please checkout this PR and give it a go on your side?

Review @edmundnoble @benhutchison 

fixes #56

### CODE REVIEW

**Comment by boggle** [comment]
@etorreborre This looks great! I'm leaving for vacation tomorrow but will try to give it a spin soon.

**Comment by edmundnoble** [comment]
This is really, really nice but I actually think it would be more valuable in cats itself. This is a very general-purpose tool.

**Comment by benhutchison** [comment]
👍 Awesome! :) 

More concrete feedback will come as well migrate codebases onto this form.

Edmund, agree it might well find wider usage, but lets get it into Eff now and demonstrate the benefits. Im happy to port to cats version if it gets wider "standardization" later.

**Comment by dispalt** [comment]
whoa, this solves a problem for sure... Ill try to check it out too.

**Comment by edmundnoble** [comment]
Sure @benhutchison, we'll see how it fares here.

**Comment by etorreborre** [comment]
Also my latest version is customized to `eff` and not applicable (for now) to more general contexts. I am indeed guiding the implicit search by indicating that I want to "extract" elements of the form `H Op R` (like `Foo |= R`). If I stay too general and just try to extract `H` I get diverging implicits (again,... How many hours of my life spent on that?).

**Comment by etorreborre** [comment]
@edmundnoble I will wait a bit before merging this for the feedback from other projects. I just want to make sure that:

 - it is working for them
 - it's not introducing a regression for previously working code

**Comment by etorreborre** [comment]
I'm merging this now. Hopefully people will open issues if that doesn't work or create regressions.

**Comment by boggle** [comment]
Thanks for working on this! I gave it a quick spin now and the diverging implicits really get in the way. Will have a second attempt at this but it looks like my current code has too many pieces that require "import Members._" in one line and not in the next.

**Comment by etorreborre** [comment]
Can I say that I'm not really surprised :-)?

**Pull request merged**
